### ISSUE TITLE
Rename EncryptedERC20 to ConfidentialERC20

### ISSUE THREAD

**Issue by PacificYield** [zama-ai/fhevm-contracts#51]
Following the release of the Inco/Circle whitepaper, would it be worth renaming `EncryptedERC20` to `ConfidentialERC20`?

**Comment by poppyseedDev** [comment]
TODO: there is only one page that needs to be updated and this is the [see all tutorials](https://github.com/zama-ai/fhevm/blob/main/docs/tutorials/see-all-tutorials.md) everything else references upon this page.
